---
- name: Create discourse IAM users
  amazon.aws.iam_user:
    name: "{{ item }}"
    state: present
    profile: aqcom
  with_items:
    - pdforums-discourse
  tags:
    - pdforums_discourse
    - aws

- name: Attach all-access S3 policy to discourse user
  amazon.aws.iam_policy:
    iam_type: user
    iam_name: pdforums-discourse
    policy_name: discourse-upload-access
    state: present
    policy_json: "{{ lookup('file', 'discourse-bucket-access.json') }}"
    profile: aqcom
  tags:
    - pdforums_discourse
    - aws

- name: Attach all-access S3 policy to discourse user
  amazon.aws.iam_policy:
    iam_type: user
    iam_name: pdforums-discourse
    policy_name: discourse-backups-access
    state: present
    profile: aqcom
    policy_json: "{{ lookup('file', 'discourse-backups-access.json') }}"
  tags:
    - pdforums_discourse
    - aws
