---
galaxy_info:
  author: Nichoplas Avenell
  description: An Ansible role to deploy an SFTP server using Docker and the atmoz/sftp image.
  company: Istic Co. <https://istic.co>

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: GPL-2.0-or-later

  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - sftp
    - docker

dependencies:
  []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
