---
# defaults file for roles/firth-sftp-docker

sftp_docker_user: sftp_docker
sftp_docker_group: sftp_docker
# Example structure for sftp_users
# sftp_users:
#   - name: user1
#     password: pass1
#     userid: 1001
#     groupid: 1001
#     bind_mounts:
#       - source: /data/user1/files
#         target: files
#         read_only: false
#       - source: /data/user1/docs
#         target: docs
#         read_only: true
