---
# Tasks performed as media user

- name: Install flexget support packages
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "{{ media_home }}/.virtualenvs/flexget_{{ ansible_python_version }}"
    virtualenv_python: python3
  loop:
    #   - encodings
    - transmissionrpc
    - cloudscraper
  tags:
    - flexget

- name: Install Flexget
  ansible.builtin.pip:
    name: flexget
    virtualenv: "{{ media_home }}/.virtualenvs/flexget_{{ ansible_python_version }}"
    virtualenv_python: python3
    version: "{{ flexget_version }}"
  tags:
    - flexget

- name: Make sure flexget config dir exists
  ansible.builtin.file:
    path: "{{ media_home }}/.flexget"
    state: directory
    owner: "{{ media_user }}"
    mode: "0755"
  tags:
    - flexget

# - ansible.builtin.template: src=flexget.yml dest={{ media_home }}/.flexget/config.yml mode=0660 owner="{{ media_user }}"
- name: Create flexget config
  ansible.builtin.copy:
    dest: "{{ media_home }}/.flexget/config.yml"
    mode: "0660"
    owner: "{{ media_user }}"
    content: "{{ water_gkhs_flexget_flexget_tasks | to_nice_yaml }}"
  tags:
    - flexget
    - flexgetconfig
