---
# Based on https://github.com/cmprescott/ansible-role-filebot
- name: Check Filebot Version
  ansible.builtin.lineinfile:
    path: "{{ media_home }}/.ansible_filebot_reg"
    regexp: ^etag
    line: etag {{ water_gkhs_filebot_filebot_version }}
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: "0644"
    create: true
  register: water_gkhs_filebot_did_filebot_update
  tags:
    - filebot

- name: Setup |  deb | download installer
  ansible.builtin.get_url:
    url: "{{ water_gkhs_filebot_filebot_deb_url }}"
    dest: "{{ water_gkhs_filebot_filebot_deb_tmp }}"
    mode: ug=rw,o=r
  when: water_gkhs_filebot_did_filebot_update.changed
  tags:
    - filebot

- name: Setup |  deb | run the installer
  become: true
  ansible.builtin.apt:
    deb: "{{ water_gkhs_filebot_filebot_deb_tmp }}"
  when: water_gkhs_filebot_did_filebot_update.changed
  tags:
    - filebot

- name: Install mediainfo library
  ansible.builtin.apt:
    pkg: libmediainfo0v5
    state: present

- name: Register licence
  ansible.builtin.copy:
    src: Filebot_Licence.psm.vault
    dest: "{{ media_home }}/.filebot_license.psm"
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: "0644"
  notify:
    - Register filebot
  tags:
    - filebot
